# Generated by Django 3.2.6 on 2021-09-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stripe_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
