# Generated by Django 3.2.6 on 2021-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_buyproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproducts',
            name='product_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='buyproducts',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
